//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ChatApplicationEntities : DbContext
    {
        public ChatApplicationEntities()
            : base("name=ChatApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblApplicationUser> tblApplicationUsers { get; set; }
        public virtual DbSet<tblMember> tblMembers { get; set; }
        public virtual DbSet<tblApplicationFriendAssociation> tblApplicationFriendAssociations { get; set; }
        public virtual DbSet<tblMessage> tblMessages { get; set; }
        public virtual DbSet<tblMessageRecipient> tblMessageRecipients { get; set; }
    
        public virtual ObjectResult<USP_OurOldMessage_Result> USP_OurOldMessage(Nullable<int> senderId, Nullable<int> receiverId)
        {
            var senderIdParameter = senderId.HasValue ?
                new ObjectParameter("SenderId", senderId) :
                new ObjectParameter("SenderId", typeof(int));
    
            var receiverIdParameter = receiverId.HasValue ?
                new ObjectParameter("ReceiverId", receiverId) :
                new ObjectParameter("ReceiverId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OurOldMessage_Result>("USP_OurOldMessage", senderIdParameter, receiverIdParameter);
        }
    }
}
