//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicationFriendAssociation
    {
        public int ApplicationFriendAssociationId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> FriendId { get; set; }
        public Nullable<int> RequestBy { get; set; }
        public Nullable<int> IsConfirm { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tblMember tblMember { get; set; }
        public virtual tblMember tblMember1 { get; set; }
        public virtual tblMember tblMember2 { get; set; }
    }
}
