//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessageRecipient
    {
        public int MessageRecipientId { get; set; }
        public Nullable<int> MessageId { get; set; }
        public Nullable<int> RecipientId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblMember tblMember { get; set; }
        public virtual tblMessage tblMessage { get; set; }
    }
}
